### ISSUE TITLE
suggestion for docs correction 

### ISSUE THREAD

**Issue by epogrebnyak** [abivia/ledger#17]
> If the business purchases a box of paper for $100 with cash (a debit account), then the account representing cash decreases by $100 and the account representing office expenses (a credit account) increases by $100.

Saw this in your docs, and thought your starting accounting example can be refined: 

- when you just buy paper you debit inventory, not expenses 
- expenses is also a debit-sided account, not a credit account 
- you credit cash and debit inventory in the example in text

**Comment by instancezero** [comment]
Thanks for pointing this out.

I've corrected the office expense account to make it a debit, but I've left the transaction going straight to an expense. In part because the purpose is to illustrate the double-entry accounting mechanism, which it does. There are far better resources out there to learn correct bookkeeping procedures. In part because it's customary here to send office expenses under $200 direct to expense. None of the businesses I've worked in inventory their office expenses unless they have a significant "shrinkage" (theft) problem.
