### ISSUE TITLE
Feature is not yet implemented.

### ISSUE THREAD

**Issue by mahmoud-adel44** [abivia/ledger#18]
array:2 [▼ // platform/plugins/accounting/src/Http/Controllers/AccountController.php:74
  "errors" => array:2 [▼
    0 => "Feature is not yet implemented."
    1 => "Account closing not yet implemented."
  ]
  "time" => 
Illuminate\Support
\
Carbon @1704729191 {#3862 ▼
    #endOfTime: false
    #startOfTime: false
    #constructedObjectId: "0000000000000f160000000000000000"
    #localMonthsOverflow: null
    #localYearsOverflow: null
    #localStrictModeEnabled: null
    #localHumanDiffOptions: null
    #localToStringFormat: null
    #localSerializer: null
    #localMacros: null
    #localGenericMacros: null
    #localFormatFunction: null
    #localTranslator: null
    #dumpProperties: array:3 [▶]
    #dumpLocale: null
    #dumpDateProperties: null
    date: 2024-01-08 15:53:11.203817 UTC (+00:00)
  }
]

what does that mean ??

**Comment by abivia** [comment]
I'm not sure if there's another way to explain this. Closing an account is not currently implemented, because the logic required to check the account and all sub-accounts for zero balances in all currencies and to close the entire account tree has not yet been developed. The workaround is to check all those accounts manually for a zero balance and then not post to them.
